### ISSUE TITLE
Blazor 3.2 Preview 1 compatibility issue

### ISSUE THREAD

**Issue by pablopioli** [Tewr/BlazorFileReader#104]
Updating to the last preview generates an error:

Microsoft.JSInterop.JSException: Blazor.platform.findMethod is not a function

**Comment by pablopioli** [comment]
I'm trying to understand the changes involved. My main question is: where is information about all those internals? Reading the Blazor source code?

**Comment by szmalec** [comment]
@pablopioli  It looks that `findMethod` has been removed in this commit: https://github.com/dotnet/aspnetcore/commit/62e2fb22e5eef6ba4be0919a2f0d9435293eac82
It looks that instead `findMethod` they now use `bindStaticMethod` (which calls `Module.mono_bind_static_method`)?

So fix will probably be to switch to that calls `Module.mono_bind_static_method`. As you can see in commited file they removed not only `findMethod` but other methods. If you don't want to wait for official fix BlazorFileReader you can temporarily workaround problem by trying to "restore" missing methods in your custom JS file, eg.:

```
Blazor.platform.findMethod = function findMethod(assemblyName, namespace, className, methodName) {
    return Module.mono_bind_static_method('[' + assemblyName + '] ' + namespace + '.' + className + ':' + methodName);
};
// (...)
// TODO: implement all missing methods
```

**UPDATE**: I have just discovered that we can set `services.AddFileReaderService(options => options.UseWasmSharedBuffer = false);` and then `ReadFileMarshalledAsync` is used instead of `ReadFileUnmarshalledAsync`. [First one](https://github.com/Tewr/BlazorFileReader/blob/1.2.0.19363/src/Blazor.FileReader/script/FileReaderComponent.ts#L196) does not use functions (eg. findMehod) from Blazor.platform and it looks it works now OK in my WASM blazor app...


It looks that changes related to Blazor are commited to following branch: https://github.com/dotnet/aspnetcore/commits/blazor-wasm

**Comment by pablopioli** [comment]
I don't mind to wait, I just find your component very useful and was trying to help (OSS can be time consuming). 

See you have most of it figured out. Thanks for your info on Blazor internals.

**Comment by Tewr** [comment]
@szmalec : `ReadFileMarshalledAsync `is the "official" way of doing things, it is using the public api of blazor. So it's more stable. But files must be translated to a b64string so it's about 30% slower. But thanks for pointing out the workaround.

`ReadFileUnmarshalledAsync` uses some internal API's which, apparently, are more prone to have breaking changes. I'll have to find another way. Reimplementing the old API is probably a bad idea. However all the `platform.read<type>field` methods still remain. They can be used to achieve the same thing, as the only reason I need to do a callback is to get my hands on a pointer to a byte array...
