### ISSUE TITLE
"Requires MonoWebAssemblyJSRuntime as the JSRuntime"

### ISSUE THREAD

**Issue by darren-zdc** [Tewr/BlazorFileReader#11]
I got an error when run it in server side blazor. 

[System.PlatformNotSupportedException] Requires MonoWebAssemblyJSRuntime as the JSRuntime

**Comment by darren-zdc** [comment]
Successfully printout the fileInfo 
```
IFileInfo.Name: exclamation.png
IFileInfo.Size: 4885
IFileInfo.Type: image/png
IFileInfo.LastModifiedDate: 2019-01-08 9:01:16 PM
Reading file...
```
Exception thrown when execute 
`while ((count = await fs.ReadAsync(buffer, 0, buffer.Length)) != 0)`

**Comment by Tewr** [comment]
Hello, thank you for your input and for taking the time to create an issue.

The exception you are seeing is defined [here](https://github.com/Tewr/BlazorFileReader/blob/6a85295d2a2c3c933d2dafa40f503592e5800813/src/Blazor.FileReader/ExtendedJsRuntime.cs#L27) and is fully expected behavior: this is a client-side library which uses non-marshalled invoke calls to read the file using the browser js runtime. Server-side this makes no sense what so ever.

Supporting Blazor server-side BlazorFileReader would be a totally different project, basically a rewrite from scratch imo. I might get to that someday though, could be fun. For now I'll just document the exception you are having in the readme for others who have the same problem.

**Comment by Tewr** [comment]
OK so I've read up a bit on server-side Blazor and it may not be a complete rewrite. It's more a matter of providing a parallel pipeline with marshalled calls. Significantly slower of course, but probably not much compared to the time it takes to transfer the serialized stream to the server (client-side this is all done in memory). Overall, probably a lot faster if something is to be done with the stream, which is generally the case.

I might look in to it if there is any more interest in using the library server-side.

**Comment by Tewr** [comment]
0.7.1 (on nuget now) has server-side support.
