### ISSUE TITLE
Removing from a List<> of uploads always removes the last upload in the list

### ISSUE THREAD

**Issue by elijahlucey** [Tewr/BlazorFileReader#151]
This could be a symptom of my own poor design choices, misunderstanding of the library/Blazor/web development, or a bug in external code, so I thought I'd try to rule out the latter by posting here.

I made [a small example project](https://github.com/elijahlucey/BlazorFileListTest) that should run out of the box in VSCode. The Readme in that repo says it all, but I'll paste it here too:

Just a simple page allowing uploads of multiple image files one by one with the ability to remove entries.

To see why I created this repository, add multiple file entries that can be visually distinguished (via filename, image content, or both) and try to remove an entry that isn't the last one (i.e. if a list contains `0.jpg`, `1.jpg`, `2.jpg`, choose any entry to delete except for `2.jpg`). No matter which entry you choose to delete, the final entry will be removed from the list.

But wait--it gets more complicated. If you try to debug this process, you'll find that the proper entry is indeed being removed from the `List<UploadViewModel>` stored in `IndexViewModel`. Thus, the bug only manifests itself through the Blazor-generated HTML; everything on the back end appears to be correct.

I am open to the possibility of this being my fault, but I also understand how new Blazor and the BlazorFileReader library are, so I have suspicions that the bug is caused by external code. Hopefully the answers will become clear soon. Thanks for reading, and thanks for making this library in the first place!

**Comment by Tewr** [comment]
Hello!

As far as I can tell you are using the library correctly.

Try reading this article on list management in blazor, it's probably related: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1#use-key-to-control-the-preservation-of-elements-and-components

Let me know if that works for you.

**Comment by Tewr** [comment]
There is a source of confusion here though. It's not really trivial, but storing a FileReference between calls to enumeratefilesasync will lead to unexpected results. If the underlying reference (in your case, the input element) changes, the file reference is no longer valid. I could probably track this and flag the file references as invalid when the underlying collection changes... I'll have to think about this.

Here https://github.com/elijahlucey/BlazorFileListTest/blob/2e64e7ad3034b1859ebacc3cf02e0758008ab1b5/Pages/UploadEditorRow.razor.cs#L22 , store a file info(using getfileinfoasync) instead of the file reference, and things might become more clear. 

edit: I saw that you are actually creating a new input for each upload, so this has nothing to to with your problem. More likely the lack of a `@key` attribute as per my comment above.

**Comment by elijahlucey** [comment]
Thanks for both replies! The first one was indeed the missing piece (I had to add @key, and the problem immediately went away both in the example code as well as my production use case). Always good when the solution is just a handful of characters long.

The second reply also helped me realize I'm never actually using anything in the file reference except for the file info, so I might as well only store the file info, especially if that's the more canonical approach.

Always great to learn! Thanks again.
