### ISSUE TITLE
[Announcement] Built-in file upload component released

### ISSUE THREAD

**Issue by Tewr** [Tewr/BlazorFileReader#166]
📰 01.10.2020 Microsoft has finally released a built-in file upload component called [InputFile](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0). An 1st-party component strongly diminishes this component's raison d'etre, and I strongly recommend all new development to use the built-in component, and current users to migrate. The natural course of action is to stop actively developing this project. If you feel that this decision is somehow wrong, feel free to comment here to convince me otherwise.

**Comment by arivera12** [comment]
This project should not be deprecated by MS inputFile because it's lacks of features compared to this library and MS have been very lazy implementing this feature since blazor exists. This is like comparing newtonsoft.json vs system.text.json. You know system.text.json lacks of tons of features and other things are not supported by default where newtonsoft.json are already builtin. Also you have already lots of samples of how to use, even drag and drop components and usage of them. I vote to not deprecate this project until MS inputFile is comparable near to this. I could suggest to create a new branch and use MS inputFile and see how easily and compatible it is with what you have implemented here.

**Comment by sven5** [comment]
I think for projects that must rely/stuck on .NET Core 3.1 there is a need for this particular component. Because the `InputFile` component is contained in .NET 5 only.

**Comment by arivera12** [comment]
> I think for projects that must rely/stuck on .NET Core 3.1 there is a need for this particular component. Because the `InputFile` component is contained in .NET 5 only.

This is a solid reason to not deprecate this project.

**Comment by Smurf-IV** [comment]
> I think for projects that must rely/stuck on .NET Core 3.1 there is a need for this particular component. Because the `InputFile` component is contained in .NET 5 only.

.Net Core 3.1 is also LTS, so it will be used for a long time in production systems.

**Comment by OliverPrivate** [comment]
Hi, 

This component is great and we've recently tried to use uploaders from SyncFusion for chunked, multiple and para uploads. It's not the best for Blazor even though many of their controls are great. Reason is it's complex to implement and maintain compared with yours and has several bugs.

If you could add chunked, para and some other more advanced features as above, plus progress bar and  I'm sure the community will favor your control.

Also, the 3.1 comments are applicable.

**Comment by arivera12** [comment]
@OliverPrivate as far I remember this library offers that out box, you can read any file as stream in chunks also with this option you can implement your own progress bar while reading the files in chunks.

**Comment by arivera12** [comment]
@Tewr has already provide awesome examples even using a dropzone/dropbox with drag and drop options, it's fully featured already.

**Comment by Tewr** [comment]
Thank you for your feedback. I'll continue working on this for the time being.
