### ISSUE TITLE
failed to load source map

### ISSUE THREAD

**Issue by ValeraBRZ** [Tewr/BlazorFileReader#181]
failed to load source map: Could not load content for https://****/FileReaderComponent.js.map:
 HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

 
 Tewr.Blazor.FileReader Version 3.0.0.20340
 
 Server-Side Blazor: in Startup.cs is only  services.AddFileReaderService();

**Comment by Tewr** [comment]
Hello, thank you for your feedback. I've noticed this minor issue before, kind of slipped through -- there are multiple issues:

The error is here:
https://github.com/Tewr/BlazorFileReader/blob/6c2f0ef3884d5e303092debaf4898d06dde3f2a0/src/Blazor.FileReader/wwwroot/FileReaderComponent.js#L377

- This references a file which is not there, correct path is missing in reference
- If the file would be correctly referenced, it would reference files which are not in the root ("../script/FileReaderJsInterop.ts" etc)

To be clear, this error message has no impact other than, of course, you cannot read the source map. Also, you get an error message, which is never very pretty.

the js build is launched here: https://github.com/Tewr/BlazorFileReader/blob/6c2f0ef3884d5e303092debaf4898d06dde3f2a0/src/Blazor.FileReader/Blazor.FileReader.csproj#L38

and configured here:
https://github.com/Tewr/BlazorFileReader/blob/6c2f0ef3884d5e303092debaf4898d06dde3f2a0/src/Blazor.FileReader/tsPreprocessor.js#L1-L7

it's an "open bar" function where any type of js processing can be done, but mostly by hand

Some possible solutions then:
- Modify the js build to output `//# sourceMappingURL=_content/Tewr.Blazor.FileReader/FileReaderComponent.js.map` instead of `//# sourceMappingURL=FileReaderComponent.js.map` and manage somehow to point the `"../script/FileReaderJsInterop.ts"` type references in the file to... what? github raw cdn? I will not include them in the package. Or I could, if I'd automate the build better and output a seperate `symbols` package with included source.
- Modify the js build to remove `//# sourceMappingURL=FileReaderComponent.js.map`
- Modify the js build to remove all comments

**Comment by ValeraBRZ** [comment]
Thank you very much. I better wait until the next release, where the bug is fixed. 
Regards,
Valera

**Comment by Tewr** [comment]
//# sourceMappingURL=FileReaderComponent.js.map was removed in this build
