### ISSUE TITLE
Some Questions: WASM vs Server Side

### ISSUE THREAD

**Issue by bytecod3r** [Tewr/BlazorFileReader#36]
Hi Guys,

I'm a noob in this subject. I have two questions:

1. What is the different between WASM and Server Side?
2. Does the loading. Net Assembly actually executes on the client browser, if yes, if we add a MethodInfo .Invoke after loading the assembly, will it be executed in the Web Browser Context?

Also when loading a .net library in my VS in "Blazor.FileReader.Wasm.Demo", it shows the following error:

```
[IFileInfo.Name: Blazor.FileReader.dll
IFileInfo.Size: 38912
IFileInfo.Type: application/x-msdownload
IFileInfo.LastModifiedDate: 05/07/2019 04:21:15
Reading file...Done reading file Blazor.FileReader.dll
.Loading assembly...
Assembly loaded.
Loading assembly contents...
Public Types:
Assembly loading of types failed: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.](url)
```
Using Visual Studio Preview.  All the project settings are as your GitHub, nothing changed.
.Net core version 3.0.0-preview4-19216-03.

Any help is appreciated.

Btw very nice project, good work!

**Comment by Tewr** [comment]
Hi. 

> 1) What is the different between WASM and Server Side?

For the scope of this project, the main difference is that when using WASM, a memory pointer is used to communicate file contents between js and the mono runtime. This means generally less overhead and better performance. For a server-side project this is not possible, the binary data has to be serialized.

> 2) Does the loading. Net Assembly actually executes on the client browser, if yes, if we add a MethodInfo .Invoke after loading the assembly, will it be executed in the Web Browser Context?

Since version 5+ of blazor, this no longer works out of the box, this is why I removed Assembly.razor from the visual menu in the demo project. I am guessing the linker removes everything that is not necessary at build time. I haven't tinkered with it since. However, IIRC, just disabling the linker step does not help. To be honest I kind of forgot about that demo, but if the answer is not in the build process, it could possible work using the [assembly load event](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyload). You would have to manually walk the dependency graph though. Let me know if you get it working.

... to actually answer your question: If you are using a WASM/client-side type project, then yes. For a server-side project, no, it would execute on the server.

**Comment by bytecod3r** [comment]
Thanks @Tewr , How about the error in my previous post? Any known version of libraries I need to use to get it working? 

Maybe you may share whats the version, etc running here https://tewr.github.io/BlazorFileReader/Assembly, I duplicate the same environment.

**Comment by Tewr** [comment]
The sources for that version is here: https://github.com/Tewr/BlazorFileReader/tree/0.5.0

**Comment by Tewr** [comment]
As for the error in your previous post, my comment referenced your error specifically. I think it may work with a bit of tinkering as I said. I personally don't know of any library or solution that does it for now. Maybe browse https://github.com/AdrienTorris/awesome-blazor and see if something relevant shows up.

**Comment by bytecod3r** [comment]
Thanks again.  Any keyword or article for writing WASM that loads code on the client's browser? I can't find much information about it.
I have created a new project in .net core 3. but the assembly .invoke runs on the server instead of the client.
Still not sure how did you code your project that runs on client.!

**Comment by Tewr** [comment]
If you use the Client template to create your project, everything is run in the browser without exception.

Just follow the guide here https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0 and choose "Blazor (client-side)" in step 8. 

I know of a project that does something similar, compiles c# in the browser and then executes it, it may be of interest to you https://github.com/Suchiman/Runny

**Comment by bytecod3r** [comment]
Cool ! Thanks
