### ISSUE TITLE
Excel demo page

### ISSUE THREAD

**Issue by PhilPJL** [Tewr/BlazorFileReader#48]
The demo source doesn't contain the Excel import page contained in the live demo.  Is this because you hit the same issue that I did when referencing EPPlus (and some other packages) where the linker fails because the parameter list is too long?

**Comment by Tewr** [comment]
Indeed! The linker fails, but it did not in that particular version which is on the live demo page. I can't remember if the parameter list size was the actual error back then, I do confirm that the linker step was the problem though. 

There are similar problems with the assembly loading demo, the linker works here but removes too much so fails at runtime as the .net standard shim is being stripped. 

I haven't taken the time to look in to it since, let me know if you find a workaround or something!

**Comment by PhilPJL** [comment]
Unfortunately there's no workaround I can see.  EPPlus references (for example) System.Data.Common (4.3.0) which defines a dependency on .NET Standard 1.2, so the linker pulls in all of .NET Standard 1.2 and then fails.  When and if there's a version of all dependent packages that themselves define dependencies against .NET Standard 2.0 (e.g a hypothetical System.Data.Common (4.4.0)) the issue would be resolved.
Or if the Blazor people fix the linker bug.   Seems like a show stopper bug to me, but what do I know?

**Comment by Tewr** [comment]
I thought maybe I'd get around with playing with the [linker configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.0). Do you think this might be a possible path? But like you say it's most likely a bug rather than a missing feature, not sure if it's filed, maybe I'll try to dig around and see if something similar is open.

**Comment by Tewr** [comment]
[this bug](https://github.com/mono/linker/issues/379) looks similar but is closed as resolved,  with some comments sayong it's not working yet (probably depends on what version of mono which was pulled in for preview 6, not sure this change made it)

Edit: I see you're already in the loop here on the follow up issue, but I'll leave it here for reference

**Comment by PhilPJL** [comment]
Yes that bug is referenced by [https://github.com/aspnet/AspNetCore/issues/11887]( https://github.com/aspnet/AspNetCore/issues/11887), which isn't scheduled to be fixed until Blazor 3.1 which makes Blazor pretty unusable for me.

**Comment by PhilPJL** [comment]
@Tewr since there's no immediate (and possibly never) resolution of the linker problem, are you able to recreate your Excel demo as a server side demo?

**Comment by Tewr** [comment]
I thought I'd just recreate it client side and disable the linker. It
seemed to work the other day when I tried. It didn't work for 0.7 but that
was a while ago, things may have changed.

Either that or the more complex method - link the rest of the app and load
epplus at runtime (so the rest of the app can be linked). Lots of work, and
with possible conflicts, but more interesting.

A server side demo, while certainly feasible, doesn't bring a lot to the
table imo (it has been possible for ages).


Den fre 2 aug. 2019 21:12PhilPJL <notifications@github.com> skrev:
