### ISSUE TITLE
Source control question

### ISSUE THREAD

**Issue by PhilPJL** [Tewr/BlazorFileReader#55]
Adding your package results in 

![image](https://user-images.githubusercontent.com/271656/62478962-529c3800-b7a4-11e9-9c5b-e0075b9d98c4.png)

but the files are actually located 

![image](https://user-images.githubusercontent.com/271656/62479125-a27aff00-b7a4-11e9-8adc-6ce56f832218.png)

so I get this message, and I can't add them to source control

![image](https://user-images.githubusercontent.com/271656/62478762-c9850100-b7a3-11e9-872e-ba7668a7267c.png)

I can ignore the warning obviously.

**Comment by Tewr** [comment]
I'd say this is expected behavior. You normally do not want to add third-party libraries nor their static assets directly to your source control, at least if you are using nuget. Referencing them this way should work fine. ~~as long as they are part of your solution directory structure~~. _Edit: solution-local package folders are no longer needed / in use by visual studio with the new csproj format._

**Comment by PhilPJL** [comment]
Maybe, but I've never seen that warning before when using various NuGet packages on ASP.NET MVC projects.
I'll try putting my test project through the DevOps build server and see what happens when the app is deployed.

**Comment by Tewr** [comment]
Let me know if you run into any problems other than the warning. There has been some packaging issues in the past, there is no detailed documentation from the blazor side on referencing static assets and how this should ideally work with nuget

**Comment by PhilPJL** [comment]
Nearly getting around to using your file reader.  I notice this:

I don't see anything scripts or css associated with Radzen in the project

![image](https://user-images.githubusercontent.com/271656/63368462-dbef6500-c375-11e9-8cae-c4fb48e6a3eb.png)

but when the app is deployed with Web Deploy, Radzen css and scripts end up in the wwwroot/_content folder.  Your script doesn't appear.

![image](https://user-images.githubusercontent.com/271656/63368655-40122900-c376-11e9-9f5d-964c1ce072f7.png)

**Comment by Tewr** [comment]
Thanks for the details! I've read up a tad on this and indeed, there has been some changes since preview7 that I missed on the subject. I simply need to move the files to wwwroot/_content and it should be ok. Or I should just remove it... In any case, this should certainly be adressed. 

Are you having any problems (runtime / publish-time) other than that annoying message and things looking weird? In the current implementation of the package the script file should not really be needed (it's packed inside the dll). Just trying to assess the emergency... :)

**Comment by PhilPJL** [comment]
No emergency yet.  Haven't got to the point of trying to upload a file :)

**Comment by Tewr** [comment]
Wasn't as easy as I thought. I found out that the `<RazorLangVersion>3.0</RazorLangVersion>` element is apparently used as a marker for static assets (even if  no razor is used), but other than that I am clueless on why the nuspec references my js. 

I'll have to rebuild the project incrementally to find out.

**Comment by Tewr** [comment]
Apparently it was my TypeScript build who added them. Ill fix this issue in the next release. THanks for your feedback.

**Comment by PhilPJL** [comment]
@Tewr 
Hi, I don't think this is fixed.  If I remove the Nuget package, FileReaderComponent.js is removed.  When I add the package back I get
![image](https://user-images.githubusercontent.com/271656/64028491-a8ad9280-cb3a-11e9-989d-5fe9ff9812c2.png)

Looks like it's not just your component that this issue.  A colleague has added Blazorise to the app

![image](https://user-images.githubusercontent.com/271656/64028724-148ffb00-cb3b-11e9-8823-1015a087b5d8.png)

**Comment by Tewr** [comment]
You are right, problem is still there in the latest release. I managed to figure out what the error was, but as I havent automated packaging I failed to account for it when building the package in the latest release. Next release should be ok...

Thank you for tracking me on this issue or I would have missed it! Ideally I should create a test that verifies the package contents, but its a lot of work and I'm hoping it should stabilize now when approaching 3.0.
