### ISSUE TITLE
Streaming a file to cloud storage

### ISSUE THREAD

**Issue by srowan** [Tewr/BlazorFileReader#74]
This is almost certainly not an actual bug, and instead will likely just illustrate my lack of understanding of streams in .Net.   I'm trying to use the azure SDK to stream file contents to blob storage without loading it all into memory first.    The azure SDK has the following signature:

```
public class BlobClient : BlobBaseClient{
    Task<Response<BlobContentInfo>> UploadAsync(Stream content);`
}
```

So the idea here is you can just give it a stream, and it will upload it for you.  So perhaps something like this:

```
using (Stream stream = await file.OpenReadAsync()) {
	await blobClient.UploadAsync(stream);
}
```
However this fails due to the restriction to async-only reads and a `NotSupportedException` is raised in `FileReaderJsInterop`  as the azure blob client attempts to call `Read` on the underlying stream.   

- Does it make sense to allow/implement `Read` when running on the server side? 
- Or Are there any workarounds available to enable this kind of scenario?  Perhaps some kind of wrapper stream?   

Also just wanted to extend a warm thank you for the work on this package, it's a lot of work creating a great file upload experience and this package takes care of so much heavy lifting!

**Comment by Tewr** [comment]
Hello! Good question.

The premise here is that your cloud API does not use ReadAsync, like it "should".

> Does it make sense to allow/implement Read when running on the server side?
> Or Are there any workarounds available to enable this kind of scenario? Perhaps some kind of wrapper stream?

You can make a wrapping stream that implements Read by waiting on ReadAsync. Simple but... blocking. Thus for intensive file upload use it will hog your server's threads for nothing. I thought about implementing this directly in the library at first (as it's "simple"), but blocking on async opens a door to a [whole](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) set of [problems](https://stackoverflow.com/questions/45034554/how-to-correctly-block-on-async-code) depending on the context of the caller, so I think I made the right decision here. I trust Eric Lippert on what is best practice on this subject, and his answer is "don't".  


The more difficult one (the "correct" way): Do not use the blob api as it does not support `ReadAsync`, use azure REST api with shared signature and PUT, optionally with [range headers](https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-the-range-header-for-blob-service-operations). it should be ok to do it in one shot if you can keep the connection open, which should be ok for small files. I am guessing that this is more or less the way `BlobClient.UploadAsync` is implemented already, only that is uses read rather than readasync on the source stream.

**Comment by Tewr** [comment]
Did you try the [CloudBlockBlob client](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient?view=azure-dotnet) ? Is it applicable for your scenario? It [looks like](https://github.com/Azure/azure-storage-net/blob/25c1aa1f24bd425e5a0c3bc5a50f13e73a3493c6/Lib/ClassLibraryCommon/Core/Util/AsyncStreamCopier.cs#L270) it  uses `ReadAsync` on the source stream.

**Comment by srowan** [comment]
I believe that is the "old" sdk.  I'm trying to stick with the newer one that will be released with dotnet core 3 as it's a complete rewrite and I expect it to be the standard / recommended sdk after dotnet 3 is released: https://github.com/Azure/azure-sdk-for-net

It seems somewhat likely that this could just be an oversight with the new SDK, as you mentioned.  I will add a bug and see what they come back with.

**Comment by Tewr** [comment]
Is it possible for you to reproduce a stacktrace from the exception? Reading the code for `UploadAsync(Stream content)`, it ends up with `sourceStream.CopyToAsync`, which should certainly call `ReadAsync` of the [`InteropFileStream`](https://github.com/Tewr/BlazorFileReader/blob/master/src/Blazor.FileReader/FileReaderJsInterop.InteropFileStream.cs). Which apparently it doesn't, so I must be following the wrong code path - or we've missed something. 

> a `NotSupportedException`is raised in `FileReaderJsInterop`

Are you sure it's not `NotImplementedException`? `NotSupportedException` is thrown by [ `Write()`](https://github.com/Tewr/BlazorFileReader/blob/28b7477d4b2c7e40c28572a13e81ca6c090332b0/src/Blazor.FileReader/FileReaderJsInterop.InteropFileStream.cs#L106) or by [ `SetLength()`](https://github.com/Tewr/BlazorFileReader/blob/28b7477d4b2c7e40c28572a13e81ca6c090332b0/src/Blazor.FileReader/FileReaderJsInterop.InteropFileStream.cs#L101).  `Read()` throws [NotImplementedException](https://github.com/Tewr/BlazorFileReader/blob/28b7477d4b2c7e40c28572a13e81ca6c090332b0/src/Blazor.FileReader/FileReaderJsInterop.InteropFileStream.cs#L58)...

**Comment by srowan** [comment]
> Are you sure it's not `NotImplementedException`?

Sorry, yes - I was going by memory - you are correct, it is `NotImplementedException`

**Comment by Tewr** [comment]
I have managed to debug this during my lunch break.

Turns out the call comes from [NonDisposingStream.Read()](
https://github.com/Azure/azure-sdk-for-net/blob/81cb4541c8dceabc339a75eb17be3dfc7a436bfe/sdk/storage/Azure.Storage.Common/src/NonDisposingStream.cs#L32)

The innerStream being our [InteropFileStream](https://github.com/Tewr/BlazorFileReader/blob/master/src/Blazor.FileReader/FileReaderJsInterop.InteropFileStream.cs).

If I understand Streams correctly, which I can't guarantee (the codebase is a bit hairy, and most of the stacktrace is lost when it's async), `CopyToAsync` calls `ReadAsync` on the `Stream` in question, which in this case is [NonDisposingStream](
https://github.com/Azure/azure-sdk-for-net/blob/81cb4541c8dceabc339a75eb17be3dfc7a436bfe/sdk/storage/Azure.Storage.Common/src/NonDisposingStream.cs) . `Stream.ReadAsync` default implementation is, more or less, a fancy `Task.Run(()=> this.Read())`.

TL&DR; [NonDisposingStream](
https://github.com/Azure/azure-sdk-for-net/blob/81cb4541c8dceabc339a75eb17be3dfc7a436bfe/sdk/storage/Azure.Storage.Common/src/NonDisposingStream.cs) does not override `ReadAsync`, thus, `Stream.ReadAsync` ends up calling `Read()`.

**Comment by Zsolt-Bendes** [comment]
@Tewr 
I'm not an expert in streams. Maybe C# 8 async stream and IAsyncDisposable solve this in the future?
Btw, awsome library :) Unfortunatly in prev 9 version I get an error. Will open a ticket with some details.

@srowan 
For streaming a file to a blob storage I create a SAS token and I stream the file content via the REST API of the blob storage. 

Something like this:
`
 var sasToken = await _httpClient.GetStringAsync("<A ws call got the sas token>");
//The stream source is from BlazorFileReader
 using (HttpContent fileStreamContent = new StreamContent(stream))
 {
     fileStreamContent.Headers.Add("x-ms-blob-type", "BlockBlob");
      var response = await _httpClient.PutAsync(sasToken, fileStreamContent;
}`

Hope this helps

**Comment by Tewr** [comment]
The fix is [merged](https://github.com/Azure/azure-sdk-for-net/issues/7456) into the azure sdk now, but I guess you'll have to stick to the method outlined by @Zsolt-Bendes until they get another version out, looks like they do it monthly more or less. Or compile the sdk yourself...

**Comment by srowan** [comment]
Wow, you are amazing, thanks!   For now I'm just streaming to memory, then writing to azure.  That will do until they release the next version.

Thanks again, and sorry for dragging you into that :)

**Comment by Tewr** [comment]
Thank you for reporting it! Azure is a very prominent platform and I think your use case shouldn't be too rare. It's great to find these kind of kinks while 3.0 is still in preview. This means devs are responsive and accept pull requests as the pressure is off. Once released they may be reluctant to fix stuff even if it's a perceived bug, as backwards compatibility is super important

**Comment by kurtzeborn** [comment]
@srowan, I wanted to share that the updated previews containing @Tewr's fix were published just now:
- [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs/12.0.0-preview.3)

Thanks @Tewr for contributing the fix!  It is greatly appreciated.
